1.Write a program that evaluates the function:
y = x2-1
at a single point. The program should request a value of x from the screen, print out the
equivalent value of y and stop.

In [1]:
x=float(input("input a number"))
y=x**2-1
y


input a number3


8.0

2.Modify your program so that it will evaluate any quadratic: y =ax2 + bx + c
You will need to ask for the coefficients from the screen.
Model solution is in file: Exercise5.2.py
Enter the coefficients used in the previous example: a=1, b=0, c=-1 and check that you get
the same answer using both programs.

In [2]:
a=float(input("input coefficient a number"))
b=float(input("input coefficient b number"))
c=float(input("input coefficient c number"))
x=float(input("input coefficient x number"))
d=a*x**2+b*x+c
d

input coefficient a number1
input coefficient b number0
input coefficient c number-1
input coefficient x number3


8.0

6.1 ######LIST######

Write a small database and some code to query it using lists.
Create a list with the names of 10 ‘friends’. Create a second matching list with their years of
birth. Ask the user to input a name. Tell him the place (index) of that person in the list, how
many friends he has in total and the year of birth of the person. The input and output should
look like this:
Enter a name: Will
You have 10 friends
Will is number 8 in your list
Will was born in 1991

In [3]:
names=["ram","raj","ravi","rahul","rahim","raju","rakesh","ramesh","will","ranbir"]
year=[91,92,93,94,95,96,97,98,1991,92,95]
name=input("Enter your friends name:")
print("you have",len(names),"friends")
index=names.index(name)
print(name,"is number",index, "in your list")
print(name, "was born in",year[index])


Enter your friends name:will
you have 10 friends
will is number 8 in your list
will was born in 1991


# create 3 lists fruits, shop, price
# output
# if you select a fruit shop name name in which it is available should be displayed with price



In [4]:
fruits=['apple','banana','mango','pineapple']
shop=[2,55,3,65]
price=[30,40,50,60]
value=input('enter fruits name:')
index1=fruits.index(value)
index2=shop[index1]
index3=price[index1]
print('you have',value,'in',index2,'shop')
print(value,'the price is',index3)


enter fruits name:apple
you have apple in 2 shop
apple the price is 30


# create 4 lists students ,roll,standard,gender
# output 
# if you select student name rollno ,gender and class should appear

In [5]:
student=['rakesh','rajesh','srivani','abhishek','srilatha','ashwini','vikesh','nikhitha']
roll=[46,65,12,34,54,64,34,89]
standard=['3rd class','4th class','5th class','6th class','7th class','8th class','9th class','10th class']
gender=['male','male','female','male','female','female','male','female']
pick=input('enter student name:')
index1=student.index(pick)
index2=roll[index1]
index3=standard[index1]
index4=gender[index1]
print('rakesh roll number is',index2)
print(pick,'studies in',index3)
print(pick,'gender is',index4)

enter student name:rakesh
rakesh roll number is 46
rakesh studies in 3rd class
rakesh gender is male


Create a 10x10 matrix of integers starting at 1 and ending at 100 as a NumPy array. The first
row is the integers 1 to 10, the second 11 to 20 etc. (Use numpy.arange() and the shape()
method). Print the matrix to the screen.
Now slice out the column from the matrix where all of the numbers end in the digit 5 (the 5th
column). Print this to the screen. It should look like this:

[ 5 15 25 35 45 55 65 75 85 95]

In [8]:
import numpy as np
mydata=np.arange(1,101,1,dtype="int")
mydata.shape=(10,10)
mydata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [9]:
print(mydata[:,4])

[ 5 15 25 35 45 55 65 75 85 95]


In [10]:
print(mydata[5,:])

[51 52 53 54 55 56 57 58 59 60]


In [11]:
print(mydata[8,3])

84


# Now slice out a sub-matrix from the original matrix to look like this:

[[35 36 37 38]
[45 46 47 48]
[55 56 57 58]]

In [18]:
print(mydata[3:6,4:8])

[[35 36 37 38]
 [45 46 47 48]
 [55 56 57 58]]


# Now convert the sub matrix to a vector to look like:
[35 36 37 38 45 46 47 48 55 56 57 58]

In [20]:
a=mydata[3:6,4:8]
a.flatten()

array([35, 36, 37, 38, 45, 46, 47, 48, 55, 56, 57, 58])

The program for exercise 6.1 would have been better done with a dictionary rather than two
lists. Repeat the exercise but using a single dictionary to hold the data. Which of the outputs
from example 6.1 cannot be generated from data stored in a dictionary and why? If you enter
a friend who is not in the list, the program will crash with a different error to the version that
used lists.

In [21]:
friends={}
friends['rakesh']='6th sept'
friends['vikesh']='8th dec'
friends['rajesh']='24th july'
friends['ramesh']='6th may'

name=input('enter friend:')
print(name, "age is",friends[name])



enter friend:rakesh
rakesh age is 6th sept
